root: true
parser: '@typescript-eslint/parser'
ignorePatterns:
  - '*.mjs'
plugins:
  - '@typescript-eslint'
env:
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
